"""empty message

Revision ID: af4c6c4e7f82
Revises: 87c1516644f3
Create Date: 2025-09-19 23:05:07.412548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4c6c4e7f82'
down_revision = '87c1516644f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=200), nullable=False))
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('url')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('url')

    # ### end Alembic commands ###
